### ISSUE TITLE
Feature: Display winner class colour and icon

### ISSUE THREAD

**Issue by Sy-zz** [TekNoLogic/teksLoot#10]
At the moment, the winner's name is displayed.  This request is to colour that name (based on the existing user colour settings) and to add the class icons.

Also perhaps the text will need a shadow so that there are no odd colour conflicts with the background colour.  (I wouldn't bother changing my default class colours, so I wouldn't care much about this)

**Comment by tekkub** [comment]
teksLoots doesn't show winners... ever...
