### ISSUE TITLE
update zhCN locale - patch 4.3

### ISSUE THREAD

**Issue by billyyao** [TekNoLogic/teksLoot#19]
Hello Mate,

Thanks for the great addon. I have udpated the Locale.lua file after 4.3 and tested for zhTW.

Please find the code below:

---

} or locale == "zhTW" and {
    ["(._)自動放棄:(.+)，因為"]  = "pass",
    ["(._)放棄了:(.+)"] = "pass",
    ["(._)選擇了貪婪:(.+)"] = "greed",
    ["(._)選擇了需求:(.+)"] = "need",
    ["(.*)選擇分解:(.+)"] = "disenchant",
} or {

---

Thanks

**Comment by tekkub** [comment]
Thanks to changes in 5.0, the locale isn't needed anymore.  Huzzah!
