### ISSUE TITLE
deDE localization

### ISSUE THREAD

**Issue by cremor** [TekNoLogic/teksLoot#2]
Following is a copy from the deDE 3.3 GlobalStrings.lua
Please include the disenchant option and update the auto pass regex to contain the female form.

 LOOT_ROLL_DISENCHANT = "%s hat für '%s' Entzauberung gewählt.";

 LOOT_ROLL_GREED = "%s hat für %s 'Gier' ausgewählt";

 LOOT_ROLL_NEED = "%s hat für %s 'Bedarf' ausgewählt";

 LOOT_ROLL_PASSED = "%s würfelt nicht für: %s";

 LOOT_ROLL_PASSED_AUTO = "%1$s passt automatisch bei %2$s, weil er den Gegenstand nicht benutzen kann.";

 LOOT_ROLL_PASSED_AUTO_FEMALE = "%1$s passt automatisch bei %2$s, weil sie den Gegenstand nicht benutzen kann.";

**Comment by cremor** [comment]
I now tried it with the following regex, but the counter on the disenchant button didn't increase.
    ["(.*) hat f\195\188r (.+) Entzauberung gew\195\164hlt"]  = "disenchant",
Shouldn't that work?

edit:
Ok, the following works:
    ["(.*) hat f\195\188r '(.+)' Entzauberung gew\195\164hlt."]  = "disenchant",

**Comment by tekkub** [comment]
deDE locale update for 3.3

Closed by 7ec38d952c501cd4b946775cfd1808b427b74a05
