### ISSUE TITLE
Suggest: interface with AtlasLoot Wishlists

### ISSUE THREAD

**Issue by SannaSK** [TekNoLogic/teksLoot#7]
Summary: suggestion to display AL Wishlist icons in the Teksloot roll box, but NOT to have Teksloot do anything automatic about the item or the roll.

Long version: Being incredibly slow about certain things, I only recently discovered the Wishlist function in AtlasLoot. Someone pointed me towards an addon called PassLoot which will interface with AL Wishlists and automatically have you roll Need or Greed or Pass on certain sets of items. I'm not really happy with this addon as I don't really like to have a 'machine' make that sort of decision for me. What if I got an upgrade in the meantime and hadn't had time to update my wishlist, but an item comes up and this addon makes me roll need on it? That's not shinie. Then I thought, "What if I could just see the wishlist icon on my Teksloot box (in the same way that AL displays a small icon next to the item if you're viewing the boss drops table) so I could say, 'oh, at one point i wanted this item, do I still want it?' and then make that call myself, on if I should roll Need or Greed or Pass?"

[s]After servers come up, I'll screenshot what I mean about AL displaying the small icon and post a picasa link.[/s] edit: http://lh4.ggpht.com/_ZdGhiK8TW6c/S5boPKUNbYI/AAAAAAAAAGI/dN7F6F_P1bI/AL-wishlist-icons.jpg

To clarify, despite repeated attempts to learn LUA, I have failed every time, and so while this sounds to me like a simple thing to do, I hope I'm not actually making a terrifically difficult suggestion. Also, I'm not asking for Teksloot to do what PassLoot does; I really don't think people are well-served by having an addon automatically roll on things /for/ them. It would just be really awesome to have that little icon pop up to remind me, 'at one point i wanted this,' so I can make my own decision on whether or not I still want this item.

Thanks for reading and thanks for making such spiffy addons~

**Comment by tekkub** [comment]
Can't this other addon just add something to the tooltip when it's displayed?  I don't do anything fancy with the tooptips, it should be a simple matter for them to do this... and it'd work with any addon that shows a tooltip.

**Comment by SannaSK** [comment]
I'm imagining something like 
http://lh4.ggpht.com/_ZdGhiK8TW6c/S6j-wcFalRI/AAAAAAAAAHo/xiSs6z_IQ5c/teksloot-suggest_01.gif
Sorry I took so long to make that image edit. I should procrastinate less : x.
