### ISSUE TITLE
Feature: Indicate when only one player has needed after all others have rolled

### ISSUE THREAD

**Issue by Sy-zz** [TekNoLogic/teksLoot#9]
The way I have teksLoot set up, the tooltip appears when a roll begins.  Then the tooltip almost immediately disappears when the item has been distributed.  I'll file a separate feature request to keep the tooltip open.

For this request, I'm curious to learn when only one person has rolled need.  Basically, I want to more easily learn if someone has ninja'd something.

**Comment by tekkub** [comment]
Ninja detection like that is best suited for it's own addon.  teksLoot is simply a replacement for the default roll frames.
